### ISSUE TITLE
根据你的思路自己实现了一下

### ISSUE THREAD

**Issue by recosky** [jinyb09017/delayActionDemo#2]
public class CallUnit2 {
    //目标行为
    private Action action;
    //目标条件
    private Queue<Valid> validQueue = new ArrayDeque<>();
    //上一个执行的valid
    private Valid lastValid;
    private static CallUnit2 instance;

    private CallUnit2() {
    }

    public static CallUnit2 getInstance() {
        if (instance == null) {
            instance = new CallUnit2();
        }
        return instance;
    }

    public CallUnit2 setNewAction(Action action) {
        clear();
        this.action = action;
        return instance;
    }

    public CallUnit2 addValid(Valid valid) {
        if(!valid.check()){
            validQueue.add(valid);
        }
        return instance;
    }

    public void doCall() {
        if(action == null){
            return;
        }
        if(lastValid != null && !lastValid.check()){
            //action.error(lastValid);
            clear();
            return;
        }
        if (validQueue.size() > 0) {
            lastValid = validQueue.remove();
            lastValid.doValid();
        } else {
            action.call();
            clear();
        }
    }

    private void clear(){
        validQueue.clear();
        lastValid = null;
        action = null;
    }
}

**Comment by jinyb09017** [comment]
这样做可以省去ActionManager的调用，是吗？其实这里还有功能好像省去了。

还有ActionManager存在的必要，是因为这里面维护了Stack<CallUnit> delaysActions = new Stack<>()的堆栈，表示验证行为里面可以嵌套目标任务的。

如果不需要的话，确实简洁很多，赞一个
